/* gpsd_config.h generated by scons, do not hand-hack. */

#ifndef GPSD_CONFIG_H

#define VERSION "3.17"

#define GPSD_URL "http://catb.org/gpsd"

/* #undef HAVE_LIBUSB */

#define HAVE_LIBRT 1

/* #undef HAVE_DBUS */

/* #undef ENABLE_BLUEZ */

#define HAVE_LINUX_CAN_H 1

#define HAVE_STDATOMIC_H 1

/* #undef HAVE_OSATOMIC_H */

#define HAVE_BUILTIN_ENDIANNESS 1

/* #undef HAVE_ENDIAN_H */

/* #undef HAVE_SYS_ENDIAN_H */

#define HAVE_SYS_UN_H 1

#define HAVE_SYS_SOCKET_H 1

#define HAVE_SYS_SELECT_H 1

#define HAVE_NETDB_H 1

#define HAVE_NETINET_IN_H 1

#define HAVE_NETINET_IP_H 1

#define HAVE_ARPA_INET_H 1

#define HAVE_SYSLOG_H 1

#define HAVE_TERMIOS_H 1

/* #undef HAVE_WINSOCK2_H */

#define HAVE_DAEMON 1

#define HAVE_STRLCPY 1

#define HAVE_STRLCAT 1

#define HAVE_CLOCK_GETTIME 1

#define HAVE_STRPTIME 1

#define HAVE_GMTIME_R 1

#define HAVE_INET_NTOP 1

#define HAVE_FCNTL 1

#define HAVE_FORK 1

/* AIVDM support */
#define AIVDM_ENABLE 1

/* Ashtech support */
#define ASHTECH_ENABLE 1

/* application binaries directory */
#define BINDIR "bin"

/* BlueZ support for Bluetooth devices */
/* #undef BLUEZ_ENABLE */

/* client debugging support */
#define CLIENTDEBUG_ENABLE 1

/* control socket for hotplug notifications */
#define CONTROL_SOCKET_ENABLE 1

/* allow gpsctl/gpsmon to change device settings */
#define CONTROLSEND_ENABLE 1

/* build with code coveraging enabled */
/* #undef COVERAGING_ENABLE */

/* enable DBUS export support */
/* #undef DBUS_EXPORT_ENABLE */

/* include debug information in build */
/* #undef DEBUG_ENABLE */

/* documents directory */
#define DOCDIR "share/doc"

/* DeLorme EarthMate Zodiac support */
#define EARTHMATE_ENABLE 1

/* EverMore binary support */
#define EVERMORE_ENABLE 1

/* fixed serial port speed */
/* #undef FIXED_PORT_SPEED */

/* fixed serial port stop bits */
/* #undef FIXED_STOP_BITS */

/* force daemon to listen on all addressses */
/* #undef FORCE_GLOBAL_ENABLE */

/* Jackson Labs Fury and Firefly support */
#define FURY_ENABLE 1

/* San Jose Navigation FV-18 support */
#define FV18_ENABLE 1

/* Garmin kernel driver support */
#define GARMIN_ENABLE 1

/* Garmin Simple Text support */
#define GARMINTXT_ENABLE 1

/* Geostar Protocol support */
#define GEOSTAR_ENABLE 1

/* GPSClock support */
#define GPSCLOCK_ENABLE 1

/* gpsd itself */
#define GPSD_ENABLE 1

/* privilege revocation group */
#define GPSD_GROUP "gps"

/* privilege revocation user */
#define GPSD_USER "gps"

/* gspd client programs */
#define GPSDCLIENTS_ENABLE 1

/* implicit linkage is supported in shared libs */
#define IMPLICIT_LINK_ENABLE 1

/* header file directory */
#define INCLUDEDIR "include"

/* build IPv6 support */
#define IPV6_ENABLE 1

/* Spectratime iSync LNRClok/GRCLOK support */
#define ISYNC_ENABLE 1

/* iTrax hardware support */
#define ITRAX_ENABLE 1

/* fetch up-to-date data on leap seconds. */
#define LEAPFETCH_ENABLE 1

/* system libraries */
#define LIBDIR "lib"

/* build C++ bindings */
#define LIBGPSMM_ENABLE 1

/* special Linux PPS hack for Raspberry Pi et al */
/* #undef MAGIC_HAT_ENABLE */

/* build help in man and HTML formats */
/* #undef MANBUILD_ENABLE */

/* manual pages directory */
#define MANDIR "share/man"

/* maximum allowed clients */
#define MAX_CLIENTS 64

/* maximum allowed devices */
#define MAX_DEVICES 4

/* turn off every option not set on the command line */
/* #undef MINIMAL_ENABLE */

/* MTK-3301 support */
#define MTK3301_ENABLE 1

/* Navcom NCT support */
#define NAVCOM_ENABLE 1

/* build with ncurses */
/* #undef NCURSES_ENABLE */

/* build support for handling TCP/IP data sources */
#define NETFEED_ENABLE 1

/* NMEA0183 support */
#define NMEA0183_ENABLE 1

/* NMEA2000/CAN support */
#define NMEA2000_ENABLE 1

/* float ops are expensive, suppress error estimates */
/* #undef NOFLOATS_ENABLE */

/* don't symbol-strip binaries at link time */
/* #undef NOSTRIP_ENABLE */

/* NTP time hinting support */
#define NTP_ENABLE 1

/* NTP time hinting via shared memory */
/* #undef NTPSHM_ENABLE */

/* NTRIP support */
#define NTRIP_ENABLE 1

/* OceanServer support */
#define OCEANSERVER_ENABLE 1

/* Motorola OnCore chipset support */
#define ONCORE_ENABLE 1

/* Disciplined oscillator support */
#define OSCILLATOR_ENABLE 1

/* build support for passing through JSON */
#define PASSTHROUGH_ENABLE 1

/* pkgconfig file directory */
#define PKGCONFIG "lib/pkgconfig"

/* PPS time syncing support */
#define PPS_ENABLE 1

/* installation directory prefix */
#define PREFIX "/usr/local"

/* build with profiling enabled */
/* #undef PROFILING_ENABLE */

/* build Python support and modules. */
/* #undef PYTHON_ENABLE */

/* coverage command for Python progs */
#define PYTHON_COVERAGE "coverage run"

/* Python module directory prefix */
/* #undef PYTHON_LIBDIR */

/* ANDROID QEMUD pipe support */
#define QEMUDPIPE_ENABLE 1

/* build QT bindings */
/* #undef QT_ENABLE */

/* version for versioned Qt */
/* #undef QT_VERSIONED */

/* allow gpsd to change device settings */
#define RECONFIGURE_ENABLE 1

/* rtcm104v2 support */
#define RTCM104V2_ENABLE 1

/* rtcm104v3 support */
#define RTCM104V3_ENABLE 1

/* system binaries directory */
#define SBINDIR "sbin"

/* build shared libraries, not static */
#define SHARED_ENABLE 1

/* export via shared memory */
/* #undef SHM_EXPORT_ENABLE */

/* SiRF chipset support */
#define SIRF_ENABLE 1

/* Skytraq chipset support */
#define SKYTRAQ_ENABLE 1

/* run tests with realistic (slow) delays */
/* #undef SLOW_ENABLE */

/* data export over sockets */
#define SOCKET_EXPORT_ENABLE 1

/* squelch gpsd_log/gpsd_hexdump to save cpu */
/* #undef SQUELCH_ENABLE */

/* Novatel SuperStarII chipset support */
#define SUPERSTAR2_ENABLE 1

/* system configuration directory */
#define SYSCONFDIR "etc"

/* cross-development system root */
/* #undef SYSROOT */

/* systemd socket activation */
/* #undef SYSTEMD_ENABLE */

/* cross-development target */
/* #undef TARGET */

/* target Python version as command */
#define TARGET_PYTHON "python"

/* time-service configuration */
/* #undef TIMESERVICE_ENABLE */

/* latency timing support */
/* #undef TIMING_ENABLE */

/* True North Technologies support */
#define TNT_ENABLE 1

/* DeLorme TripMate support */
#define TRIPMATE_ENABLE 1

/* Trimble TSIP support */
#define TSIP_ENABLE 1

/* u-blox Protocol support */
#define UBLOX_ENABLE 1

/* udev rules directory */
#define UDEVDIR "/lib/udev"

/* libusb support for USB devices */
/* #undef USB_ENABLE */

/* include xgps and xgpsspeed. */
/* #undef XGPS_ENABLE */


#define GPSD_CONFIG_H
#endif /* GPSD_CONFIG_H */
